services:
  - type: web
    name: whatsapp-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: VERIFY_TOKEN
        value: my_verify_token  # same token you set in Meta webhook
      - key: WHATSAPP_TOKEN
        sync: false             # put in Render dashboard -> Environment Variables
      - key: PHONE_NUMBER_ID
        sync: false             # put in Render dashboard -> Environment Variables
